echo 'mixed x mixed'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/mixed/una-test-1-00010000.pyrnn.gz 'test/*/*.bin.png'
echo 'mixed x mns'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/mixed/una-test-1-00010000.pyrnn.gz 'test/mns/*.bin.png'
echo 'mixed x sel'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/mixed/una-test-1-00010000.pyrnn.gz 'test/sel/*.bin.png'
echo 'mixed x sjd'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/mixed/una-test-1-00010000.pyrnn.gz 'test/sjd/*.bin.png'
echo 'mixed x yrk'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/mixed/una-test-1-00010000.pyrnn.gz 'test/yrk/*.bin.png'
echo 'sjd x mixed'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/sjd/sjd-test-1-00010000.pyrnn.gz 'test/*/*.bin.png'
echo 'sjd x mns'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/sjd/sjd-test-1-00010000.pyrnn.gz 'test/mns/*.bin.png'
echo 'sjd x sel'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/sjd/sjd-test-1-00010000.pyrnn.gz 'test/sel/*.bin.png'
echo 'sjd x sjd'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/sjd/sjd-test-1-00010000.pyrnn.gz 'test/sjd/*.bin.png'
echo 'sjd x yrk'
/Users/niko/anaconda3/envs/ocropus_env/bin/ocropus-rpred -r -q --probabilities -Q 4 -m ./models/sjd/sjd-test-1-00010000.pyrnn.gz 'test/yrk/*.bin.png'